### PR TITLE
Fix installation instruction

### PR DESCRIPTION
**Pull request by gernest**

### CODE REVIEW

**Comment by AndreasBriese** [comment]
fixed

**Comment by gernest** [comment]
@AndreasBriese  If you don't mind could yyou explain why you closed this and yet I see exactly the actual changes on your README? Rather than merging .

This was not supposed to be an issue, but a PR. I took my time to test and install and prepare the PR, so maybe it will good to know why.

**Comment by AndreasBriese** [comment]
Sorry, i didn’t wanted to offend you.

I thought fixing it and closing the issue is the usual way to deal with issues ?

Again sorry, but what would have been appropriate from your perspective?

Andreas

Am 17.04.2016 um 10:53 schrieb Geofrey Ernest notifications@github.com:

**Comment by gernest** [comment]
@AndreasBriese This is not an Issue. It is a pull request. Which Means I did take some time to test and write the changes.

The right things is, You merge if the changes are right. And there is no need to delete just closes it. Honestly I am offended, but seeing your response then I understand.

**Pull request closed without merging**
